name: Deploy

on:
  push:

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --no-restore

      - name: Run tests
        run: dotnet test --no-build --verbosity normal
        continue-on-error: false

        
      - name: Execute push
        run: |
          dotnet nuget add source \
            --username MatteoCirio \
            --password ${{"secrets.PacketToken"}} \
            --store-password-in-clear-text \
            --name github "http://nuget.pkg.github.com/MatteoCirio/index.json"

