name: HelloWorld
run-name: ${{github.actor}} is starting github action

on:
  push

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    name: test
    steps:
     - run: echo "ciao a tutti"
     - uses: action/checkout@v4
     - run: ls